services:
  - type: web
    name: whale-radar-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: CMC_API_KEY
        value: your_coinmarketcap_api_key
      - key: TELEGRAM_TOKEN
        value: your_telegram_bot_token
      - key: ADMIN_ID
        value: "123456789"
      - key: ADMIN_USERNAME
        value: your_admin_username
      - key: USDT_WALLET
        value: your_usdt_wallet_address
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com
      - key: PORT
        value: "5000"
